apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-cluster
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: redis-test

  template:
    metadata:
      name: '{{environment}}-cluster'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: redis-apps
      sources:
        - repoURL: https://github.com/mminichino/helm-charts.git
          targetRevision: 0.1.12
          chart: redis-cluster
          helm:
            valueFiles:
              - $values/environments/{{environment}}/cluster.yaml
        - repoURL: https://github.com/mminichino/redis-demo-apps.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{environment}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
