apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-demo-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: redis-apps
  sources:
    - repoURL: https://helm.redis.io
      targetRevision: 7.22.0-17
      chart: redis-enterprise-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: 'redis-demo'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
